### ISSUE TITLE
"复盘"这个词组打了好几遍为什么不会出现到候选中

### ISSUE THREAD

**Issue by awaken233** [ssnhd/rime#101]
小鹤双拼+mac

打了好几遍还是覆盘出现在第一个. 
<img width="424" alt="image" src="https://github.com/ssnhd/rime/assets/18060521/ebec7673-490a-4bde-9505-f884c7c4bbbc">

期望: 复盘出现默认候选中

按 Shift+Fn+Delete 键（第三方键盘按 Control+Delete）删除默认的"覆盘"也没有什么变化?

**Comment by Chfeng2021** [comment]
感恩有您，我将尽快与您联系。

**Comment by hsqStephenZhang** [comment]
+1

**Comment by plutotree** [comment]
我试了下，输入很多次之后，的确也没有记忆

**Comment by suibianzai** [comment]
因为本来就在词库里吧
shift+Fn+Delete“只能从用户词典中删除词组，词库里词组只会取消其调频顺序。”
<img width="876" alt="截屏2024-09-26 19 29 13" src="https://github.com/user-attachments/assets/5a96e63e-2ff3-4ded-a513-cc2c6f242397">

**Comment by awaken233** [comment]
> 因为本来就在词库里吧
> shift+Fn+Delete“只能从用户词典中删除词组，词库里词组只会取消其调频顺序。”
> <img width="876" alt="截屏2024-09-26 19 29 13" src="https://github.com/user-attachments/assets/5a96e63e-2ff3-4ded-a513-cc2c6f242397">
> 

我是输入了复盘，下次再输入他不记忆是怎么回事？

**Comment by suibianzai** [comment]
> > 因为本来就在词库里吧
> > shift+Fn+Delete“只能从用户词典中删除词组，词库里词组只会取消其调频顺序。”
> > <img alt="截屏2024-09-26 19 29 13" width="876" src="https://private-user-images.githubusercontent.com/42022663/371118323-5a96e63e-2ff3-4ded-a513-cc2c6f242397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjI0OTIsIm5iZiI6MTcyNzM2MjE5MiwicGF0aCI6Ii80MjAyMjY2My8zNzExMTgzMjMtNWE5NmU2M2UtMmZmMy00ZGVkLWE1MTMtY2MyYzZmMjQyMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE0NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMmZkNGRjZGM2N2I1ZWM4MDIwZTFkNzE3NTNiNGQxZGZiYTU2NDdkOGU4NThhZjk5MzI0MzhjNTE1NWIzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uSWa3748rwlvdFfa-0bI5AGw5BUfs3jWXz_589UlRIA">
> 
> 我是输入了复盘，下次再输入他不记忆是怎么回事？

说明你没开启自动造词/调频 本配置下怎么开启我忘了 研究了一下没有找到~

**Comment by awaken233** [comment]
> > > 因为本来就在词库里吧
> > > shift+Fn+Delete“只能从用户词典中删除词组，词库里词组只会取消其调频顺序。”
> > > <img alt="截屏2024-09-26 19 29 13" width="876" src="https://private-user-images.githubusercontent.com/42022663/371118323-5a96e63e-2ff3-4ded-a513-cc2c6f242397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjI0OTIsIm5iZiI6MTcyNzM2MjE5MiwicGF0aCI6Ii80MjAyMjY2My8zNzExMTgzMjMtNWE5NmU2M2UtMmZmMy00ZGVkLWE1MTMtY2MyYzZmMjQyMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE0NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMmZkNGRjZGM2N2I1ZWM4MDIwZTFkNzE3NTNiNGQxZGZiYTU2NDdkOGU4NThhZjk5MzI0MzhjNTE1NWIzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uSWa3748rwlvdFfa-0bI5AGw5BUfs3jWXz_589UlRIA">
> > 
> > 
> > 我是输入了复盘，下次再输入他不记忆是怎么回事？
> 
> 说明你没开启自动造词/调频 本配置下怎么开启我忘了 研究了一下没有找到~

再请教个问题， 我有两台mac，都使用本项目中readme 所说的 icloud 同步词库，这个同步是备份，还是自动合并词库呢？
- 备份：一个设备先点击同步，后点击同步的设备会覆盖先前的词库
- 自动合并两台设备中差异的词库

**Comment by suibianzai** [comment]
> > > > 因为本来就在词库里吧
> > > > shift+Fn+Delete“只能从用户词典中删除词组，词库里词组只会取消其调频顺序。”
> > > > <img alt="截屏2024-09-26 19 29 13" width="876" src="https://private-user-images.githubusercontent.com/42022663/371118323-5a96e63e-2ff3-4ded-a513-cc2c6f242397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjI0OTIsIm5iZiI6MTcyNzM2MjE5MiwicGF0aCI6Ii80MjAyMjY2My8zNzExMTgzMjMtNWE5NmU2M2UtMmZmMy00ZGVkLWE1MTMtY2MyYzZmMjQyMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE0NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMmZkNGRjZGM2N2I1ZWM4MDIwZTFkNzE3NTNiNGQxZGZiYTU2NDdkOGU4NThhZjk5MzI0MzhjNTE1NWIzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uSWa3748rwlvdFfa-0bI5AGw5BUfs3jWXz_589UlRIA">
> > > 
> > > 
> > > 我是输入了复盘，下次再输入他不记忆是怎么回事？
> > 
> > 
> > 说明你没开启自动造词/调频 本配置下怎么开启我忘了 研究了一下没有找到~
> 
> 再请教个问题， 我有两台mac，都使用本项目中readme 所说的 icloud 同步词库，这个同步是备份，还是自动合并词库呢？
> 
> * 备份：一个设备先点击同步，后点击同步的设备会覆盖先前的词库
> * 自动合并两台设备中差异的词库

不知道 没有用过icloud同步功能，你可以自己搜索关键字查找类似的讨论，比如我搜到：
https://github.com/rime/squirrel/issues/509

**Comment by awaken233** [comment]
> > > > > 因为本来就在词库里吧
> > > > > shift+Fn+Delete“只能从用户词典中删除词组，词库里词组只会取消其调频顺序。”
> > > > > <img alt="截屏2024-09-26 19 29 13" width="876" src="https://private-user-images.githubusercontent.com/42022663/371118323-5a96e63e-2ff3-4ded-a513-cc2c6f242397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjI0OTIsIm5iZiI6MTcyNzM2MjE5MiwicGF0aCI6Ii80MjAyMjY2My8zNzExMTgzMjMtNWE5NmU2M2UtMmZmMy00ZGVkLWE1MTMtY2MyYzZmMjQyMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE0NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMmZkNGRjZGM2N2I1ZWM4MDIwZTFkNzE3NTNiNGQxZGZiYTU2NDdkOGU4NThhZjk5MzI0MzhjNTE1NWIzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uSWa3748rwlvdFfa-0bI5AGw5BUfs3jWXz_589UlRIA">
> > > > 
> > > > 
> > > > 我是输入了复盘，下次再输入他不记忆是怎么回事？
> > > 
> > > 
> > > 说明你没开启自动造词/调频 本配置下怎么开启我忘了 研究了一下没有找到~
> > 
> > 
> > 再请教个问题， 我有两台mac，都使用本项目中readme 所说的 icloud 同步词库，这个同步是备份，还是自动合并词库呢？
> > 
> > * 备份：一个设备先点击同步，后点击同步的设备会覆盖先前的词库
> > * 自动合并两台设备中差异的词库
> 
> 不知道 没有用过icloud同步功能，你可以自己搜索关键字查找类似的讨论，比如我搜到： [rime/squirrel#509](https://github.com/rime/squirrel/issues/509)

ok 谢谢

**Comment by awaken233** [comment]
https://github.com/rime/squirrel/issues/437

**Comment by Chfeng2021** [comment]
感恩有您，我将尽快与您联系。

**Comment by awaken233** [comment]
直接说解决方案:
- 去 Rime 项目的 github 仓库下载最新的 [essay.txt](https://github.com/rime/rime-essay/blob/master/essay.txt) 文件, 复制到共享配置目录 (不是用户配置目录) `/Library/Input\ Methods/Squirrel.app/Contents/SharedSupport/` 重新部署一下即可.

问题原因: 简繁转换的问题, 覆被记忆成了复

当前鼠须管的配置使用的是繁体词库, 输入法呈现的候选词会经过引 opencc 进行繁转简的. 所以替换一下最新的 essay.txt 是可以解决的.
- simplifier(繁转简) -> uniquifier(去重) -> "simplifier@emoji_suggestion"(emoji 表情建议)

其他解决方案:
- 升级输入法, 应该会自动升级 essay.txt 文件
- 切换方案. 找一个码表为简体的拼音输入方案，这样就不用过 opencc
- 其他变通解决方案...
