### ISSUE TITLE
全角模式下 中文输入英文单词的问题

### ISSUE THREAD

**Issue by LanSnowZ** [ssnhd/rime#112]
在中文全角输入状态下临时输入英文单词时，单词下会出现横线例如
<img width="101" alt="image" src="https://github.com/ssnhd/rime/assets/90588095/bc837c32-3651-4253-9000-dd24cb05a25d">
此时输入回车，会出现Ｌａｔｅｘ这种全角英文，但是我想输入的是Latex
请问如何解决，谢谢！

**Comment by Chfeng2021** [comment]
感恩有您，我将尽快与您联系。

**Comment by LanSnowZ** [comment]
已经找到了解决办法，是设置里面的ascii_mode和ascii_punct搞混了，修正之后变为正确
