### ISSUE TITLE
请问这套方案怎么在window小狼毫里面部署？

### ISSUE THREAD

**Issue by suibianzai** [ssnhd/rime#114]
在mac上使用了感觉比凇雾顺手，而且不用另外配置小鹤双拼，最近PC上装了小狼毫，请问直接把配置文件copy进去可以使用么？

**Comment by Chfeng2021** [comment]
感恩有您，我将尽快与您联系。

**Comment by suibianzai** [comment]
实测可以使用，应该只有皮肤文件weasel.custom.yaml和squrrel.custom.yaml不通用
