### ISSUE TITLE
请问关于英文的排序权重怎么调到中文后面？

### ISSUE THREAD

**Issue by WROIATE** [ssnhd/rime#29]
![image](https://user-images.githubusercontent.com/44677306/126097680-ca6d45d2-65b4-474e-a50a-18aa17c40f1f.png)

如图，当我打“我们”这个词时“women”会被提到前面。如何让英文排在第二或第三候选位？

**Comment by maomiui** [comment]
以朙月拼音简化字为例：打开 `luna_pinyin_simp.custom.yaml`，找到 `initial_quality`，修改后面的数字。

**Comment by WROIATE** [comment]
> 以朙月拼音简化字为例：打开 `luna_pinyin_simp.custom.yaml`，找到 `initial_quality`，修改后面的数字。

这个我试过了，我改到2或者3都没用
![image](https://user-images.githubusercontent.com/44677306/126150035-be158e9c-22af-4016-8401-90140c358d4d.png)

**Comment by maomiui** [comment]
试试 `-4`

**Comment by WROIATE** [comment]
> 试试 `-4`

可以了，什么情况呢？-4代表什么呢？
