### ISSUE TITLE
明月简频和小鹤双拼下叠字不生效

### ISSUE THREAD

**Issue by Jacobax** [ssnhd/rime#30]
试了展示图中的「垚」字，tututu不在侯选项中，试了几个其它叠字也没有，其它方案没试
Big Sur11.4，鼠须管0.15.2

**Comment by maomiui** [comment]
已修复，请查看 [2021-07](https://github.com/maomiui/rime#2021-07)

**Comment by Jacobax** [comment]
> 已修复，请查看 [2021-07](https://github.com/maomiui/rime#2021-07)

不如弄个拆字词库吧如果不麻烦的话，网上找的一个拆字词库拼音是连着的，双拼用不了
http://gerry.lamost.org/blog/?p=296003

**Comment by maomiui** [comment]
不好意思，我不会用双拼，故这方面请用户自行添加较好。
