### ISSUE TITLE
可否增加手动中英混输的功能

### ISSUE THREAD

**Issue by hicaicai** [ssnhd/rime#33]
谢谢开发者提供这么方便的脚本,对于小白来讲太好用了,感谢,感谢.

不过我想问下有没有办法可以增加一个中英混输功能, 比如说我想输入macbook, 
是否可以在英文单词前加上我们用不到的“V”键,或者其他键, （“V”键通常在简体拼音输入下首字母暂时用不到）
所以我们能不能输入 Vmacbook,这样自动上屏幕就是 macbook, 
通过这种来实现中英混输的功能,来避免词典没有包括的词汇,也能避免想输入英文时有中文词汇干扰.
我自己也有想过通过增加表情的方式添加,但那样似乎很麻烦.
另外我好像不能自己添加词汇, 词典里没有 you 这个单词,我试着添加进去, 发现不起作用.

**Comment by maomiui** [comment]
1. 支持中英混输，没有出现英文是因为 `easy_en.dict.yaml` 里缺少你所需要的词汇（可自行加入英文词汇），或是因为该词汇没有被使用过，从而排序再很后面，此时需要翻页多次找到。
2. 快速输入常用词汇短语，将词汇加入 `custom_phrase.txt`。举例：打开 `custom_phrase.txt`，根据自己需求设置快捷短语（例如输入 `mac`，输出 `MacBook`），格式文本里有说明。

**Comment by hicaicai** [comment]
好的,谢谢开发者

**Comment by hicaicai** [comment]
感谢开发者, 我已经找到临时英文输入方法了,另外我想问下可否借用您的内容介绍这个输入法
patch:
"recognizer/patterns/veng": "^v.*$"
"engine/segmentors/@before last": affix_segmentor@veng
veng:
tag: veng
prefix: "v"
tips: "英语输入"

**Comment by maomiui** [comment]
我不是该输入法开发者，只是汇集到一起让别人方便实用，代码开源可随意使用。

**Comment by hicaicai** [comment]
好的,谢谢您让我们可以一键导入方便使用

**Comment by hicaicai** [comment]
兄弟, 有没有办法把这串代码改成回车上屏啊, 现在可以临时输入英文,但每次空格就自动上屏了, 我想继续输入又重新操作,所以能否在临时英文输入状态改成回车上屏, 或者在此状态下禁用space上屏
patch:
"recognizer/patterns/veng": "^v.*$"
"engine/segmentors/@before last": affix_segmentor@veng
veng:
tag: veng
prefix: "v"
tips: "英语输入"
