### ISSUE TITLE
两个问题：二三候选字，缺韵母

### ISSUE THREAD

**Issue by aaron2wh** [ssnhd/rime#37]
如何设置二三候选字的快捷键？比如我习惯用「；'」来选择二三候选字。
如何在缺省韵母的时候打出字来。比如在其他输入法打「bir」就可以出来「比如」，「iul」就可以「出来」，「t」就可以打出「他」来
如果能解决这两个问题，我就彻底放弃手心输入法了。

**Comment by aaron2wh** [comment]
忘了说，我是用自然码双拼

**Comment by maomiui** [comment]
快捷键可参考文内目录，个人词库需要慢慢积累（本人不用双拼所以无法提供有效解答），最后没必要放弃某个输入法，哪个用着舒服就用哪个。

**Comment by aaron2wh** [comment]
我是小白，可以帮忙看一下如何实现这两个功能吗？尤其是二三候选字，这个跟双拼还是全拼没有关系

**Comment by maomiui** [comment]
例如将下面代码放置在 `default.custom.yaml` 里 `key_binder/bindings:` 下即可。
```
      - {accept: semicolon, send: 2, when: has_menu}  # 候选2 用分号
      - {accept: apostrophe, send: 3, when: has_menu} # 候选3 用单引号
```

**Comment by aaron2wh** [comment]
这么做了，发现没有效果啊，你试过吗？好奇怪
