### ISSUE TITLE
如何设置"动态输入时间"在候选词中出现的顺序? 

### ISSUE THREAD

**Issue by abestwyc** [ssnhd/rime#52]
您好! 在提问前必须感谢您的配置方案! 比官方的"调教指南"清晰实用的多!

---

现在想实现的是始终置顶动态时间, 日期?

非常感谢!

**Comment by abestwyc** [comment]
您好! 在提问前必须感谢您的配置方案! 比官方的"调教指南"清晰实用的多!

---

现在想实现的是始终置顶动态时间, 日期?

非常感谢!

**Comment by abestwyc** [comment]
抱歉我可能没有描述清楚自己的问题, 在默认的输入"rq"显示动态日期, 这个排名是默认靠前的; 但如果把原来的"rq"更换为"date", 就会出现以下情况:

- 这种方式日期输入更靠前一些 ![CleanShot 2022-01-26 at 01 00 32](https://user-images.githubusercontent.com/56793908/151024180-2c0feac2-3ea8-428f-90c0-0e8e7a8f1506.png)

- 我暂时能想到的一种不完善的解决方案![CleanShot 2022-01-26 at 01 04 02](https://user-images.githubusercontent.com/56793908/151024173-0a922a5f-e37f-4be9-97ad-4621361a4ece.png)

**Comment by ssnhd** [comment]
打开输入方案配置文件找到 `initial_quality: -0.5`，修改后面的数字调整英文候选词位置；中文目前不知道如何修改或是否支持，待解决。
