### ISSUE TITLE
请教一下: 如何知道自己是否成功删除错词?

### ISSUE THREAD

**Issue by abestwyc** [ssnhd/rime#54]
尊敬的开发者您好!
- 删除错词这个功能很实用, 但是按"Shift+Fn+Delete"后并不知道是否成功删除;
- 能否增添一个提示? 或者有木有可以手动检查是否删除成功的方式?

**Comment by ssnhd** [comment]
> 尊敬的开发者您好!
> 
> * 删除错词这个功能很实用, 但是按"Shift+Fn+Delete"后并不知道是否成功删除;
> * 能否增添一个提示? 或者有木有可以手动检查是否删除成功的方式?

开发者是 [lotem](https://github.com/rime/squirrel)。删除错词无需提示，个人新词删除时直接可以看到消失；如果是词库内包含的，默认会删除其词频顺序（也就是不会靠前）。
