### ISSUE TITLE
关于此套配置如何在Linux下进行使用的疑问

### ISSUE THREAD

**Issue by suenchunyu** [ssnhd/rime#59]
首先非常感谢Owner能够提供如此优秀的配置文件并分享出来，早先我在Mac OS下也一直是这套配置的受益者，如今整体的工作环境切换到了Linux，我想咨询下如何在Fcitx后端的Rime上使用这套配置，非常感谢！

**Comment by 1994** [comment]
https://wiki.archlinux.org/title/Rime_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)

**Comment by xiaod-dev** [comment]
字体文件ubuntu下可以直接双击打开安装，其他的词库好像生效了，但是皮肤不能用。
方法是直接把配置文件全部复制到~/.config/ibus/rime下
