### ISSUE TITLE
大佬方便编译一个M1最新版本的安装包么

### ISSUE THREAD

**Issue by Mircc** [ssnhd/rime#65]
我编译了不知道怎么打包给别人用，因为我有多台MacBook

官网的版本是去年的了，我看期间修复不少bug

**Comment by xCss** [comment]
https://share.weiyun.com/5uaI7aGd 帮转

**Comment by Mircc** [comment]
> https://share.weiyun.com/5uaI7aGd 帮转

app放入应用程序运行后没有反应

**Comment by xCss** [comment]
> > https://share.weiyun.com/5uaI7aGd 帮转
> 
> app放入应用程序运行后没有反应

扔进去后重启电脑试试，我是重启了电脑才有的

**Comment by Mircc** [comment]
> app放入应用程序运行后没有反应

谢谢老哥，我研究了，放入系统的/Library/Input Methods 可以了
