### ISSUE TITLE
如何对rime预设快捷键进行覆盖，比如 control+ `  ，这个和vscode的一个快捷键冲突了

### ISSUE THREAD

**Issue by we-del** [ssnhd/rime#84]

**Comment by we-del** [comment]
已解决，查看  文档 ： https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E9%BB%98%E8%AA%8D%E8%8B%B1%E6%96%87%E8%BC%B8%E5%87%BA

**Comment by jarrycf** [comment]
在default.custom.yaml 中修改
patch:
  switcher:
    caption: 〔方案選單〕
    hotkeys:
      - Control+Shift+F12
