### ISSUE TITLE
开启英文输入联想补全后，“sj”无法出来时间

### ISSUE THREAD

**Issue by xiaozixun** [ssnhd/rime#94]
rq和xq倒是没有问题，只有“sj”不行。（应该是英文输入联想补全的锅）

顺便问一下，有符号自动补全这个功能吗？

**Comment by Chfeng2021** [comment]
感恩有您，我将尽快与您联系。

**Comment by xiaozixun** [comment]
忘了说了，我是win11

**Comment by suibianzai** [comment]
> 忘了说了，我是win11

请问你后来解决了么？我也是打sj和xq无法显示时间和星期

**Comment by xiaozixun** [comment]
> 请问你后来解决了么？我也是打sj和xq无法显示时间和星期

这个一年没更新了，我换了另一个配置，那个配置可以实现。

**Comment by suibianzai** [comment]
> > 请问你后来解决了么？我也是打sj和xq无法显示时间和星期
> 
> 这个一年没更新了，我换了另一个配置，那个配置可以实现。

请问你换的哪个配置？我也用过其他的 但是打字都没有这个配置舒服

**Comment by xiaozixun** [comment]
> 请问你换的哪个配置？我也用过其他的 但是打字都没有这个配置舒服

https://github.com/iDvel/rime-ice

**Comment by suibianzai** [comment]
> > 请问你换的哪个配置？我也用过其他的 但是打字都没有这个配置舒服
> 
> https://github.com/iDvel/rime-ice

好吧 这个用过 不是很适合我 谢谢回复！
