### ISSUE TITLE
自定义短语权重不起作用

### ISSUE THREAD

**Issue by awaken233** [ssnhd/rime#98]
![image](https://github.com/ssnhd/rime/assets/18060521/1ea4ede8-e50d-43f0-ab7d-ab49e2282a26)
默认的自定义短语配置, 使用的小鹤双拼方案.
期望我测试的短语出现的位置在第三个候选的位置, 但是实际的位置是1

**Comment by Chfeng2021** [comment]
感恩有您，我将尽快与您联系。

**Comment by awaken233** [comment]
是不是我对这里权重理解有问题, 权重不是候选次序, 如果我想指定某些自定义短语的候选次序如何设置呢

**Comment by suibianzai** [comment]
> 是不是我对这里权重理解有问题, 权重不是候选次序, 如果我想指定某些自定义短语的候选次序如何设置呢

custom_phrase.txt这个自定义词典里面的权重数字并不代表侯选顺序，数字越大，权重越大，就越靠前。顺序无法设定。
